import { writeFileSync, readFileSync, mkdirSync, copyFileSync, cpSync } from 'node:fs';
import { resolve, dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const outputArg = process.argv.indexOf('--out');
const output = outputArg === -1 ? root : resolve(process.argv[outputArg + 1]);
mkdirSync(output, { recursive: true });
const external = 'target="_blank" rel="noopener noreferrer"';
const company = 'https://www.linkedin.com/company/mosaic-cic';
const phil = 'https://www.linkedin.com/in/philpegram';
const arrow = '<span class="arrow" aria-hidden="true">↗</span>';
const mark = `<svg viewBox="0 0 100 76" fill="none" aria-hidden="true"><path d="M4 7 29 18 46 59 4 72Z" fill="#b27a13"/><path d="m10 3 36 16v31Z" fill="#daa626"/><path d="m52 20 41-17-41 35Z" fill="#bd871b"/><path d="m53 45 43-35-27 53Z" fill="#187848"/><path d="m75 65 21-43v51Z" fill="#075931"/><path d="m32 24 14 34v-27Z" fill="#c99521"/></svg>`;
const brand = `<a class="brand" href="./index.html" aria-label="MOSAIC CIC home">${mark}<span class="brand-name">MOSAIC<span class="sr-only"> CIC</span><small>PIECES FOR CHANGE</small></span></a>`;
const navLinks = [['index.html', 'Home'], ['approach.html', 'Our approach'], ['phil-pegram.html', 'Phil Pegram'], ['contact.html', 'Get in touch']];
const nav = (file) => navLinks.map(([href, label]) => `<a href="./${href}"${file === href ? ' aria-current="page"' : ''}${href === 'contact.html' ? ' class="nav-contact"' : ''}>${label}</a>`).join('');
const header = file => `<a class="skip-link" href="#main">Skip to content</a><header class="site-header wrap">${brand}<nav class="desktop-nav" aria-label="Main navigation">${nav(file)}</nav><div class="header-controls"><label class="sr-only" for="colour-theme">Colour theme</label><select id="colour-theme" class="theme-toggle" hidden><option value="system">System</option><option value="light">Light</option><option value="dark">Dark</option></select><button class="menu-toggle" aria-controls="mobile-nav" aria-expanded="false" hidden>Menu</button></div></header><nav id="mobile-nav" class="mobile-nav" aria-label="Mobile navigation" hidden>${nav(file)}</nav><noscript><nav class="mobile-nav" aria-label="Navigation without JavaScript">${nav(file)}</nav></noscript>`;
const footer = `<footer class="site-footer wrap"><div class="footer-top"><div>${brand}<p>Researching barriers to opportunity.<br>Building with communities in the North West.</p></div><nav class="footer-links" aria-label="Footer navigation"><a href="./approach.html">Our approach</a><a href="${company}" ${external}>MOSAIC on LinkedIn ${arrow}</a><a href="./phil-pegram.html">Meet Phil Pegram</a><a href="${phil}" ${external}>Phil on LinkedIn ${arrow}</a><a href="./contact.html">Get in touch</a><a href="./approach.html#standards">Our research commitments</a></nav></div><div class="footer-wordmark" aria-hidden="true">MOSAIC.</div><div class="footer-bottom"><p>© 2026 MOSAIC CIC. Pieces for Change.<br>North West England</p><nav class="footer-policies" aria-label="Site policies"><a href="./privacy.html">Privacy</a><a href="./accessibility.html">Accessibility</a><a href="#top">Back to top ↑</a></nav></div></footer>`;
const cta = `<section class="contact-banner"><div class="wrap"><div><p class="eyebrow">Work with MOSAIC</p><h2 style="margin-top:var(--space-4)">What’s getting in the way<br>in your community?</h2><p>Tell us about the barrier, who it affects and what you’ve already tried.</p></div><a class="button" href="./contact.html">Start a conversation ${arrow}</a></div></section>`;
const breadcrumb = label => `<p class="breadcrumb"><a href="./index.html">Home</a> / ${label}</p>`;

const pages = [
  {
    file: 'index.html', title: 'MOSAIC CIC | Pieces for Change | Phil Pegram',
    description: 'MOSAIC CIC researches barriers to work, skills and opportunity in North West England. Founded by insights leader and DBA researcher Phil Pegram.',
    body: `
<section class="hero wrap" aria-labelledby="hero-title">
  <div class="hero-meta"><p class="eyebrow">Community-led research · North West England</p><span class="eyebrow">Evidence. Participation. Action.</span></div>
  <div class="hero-layout">
    <div class="hero-copy"><h1 id="hero-title"><span>Pieces for</span><span class="highlight">change.</span></h1>
      <p>We research what stops people accessing work, skills and opportunity. Then we build practical responses with communities across the North West.</p>
      <div class="hero-actions"><a href="./approach.html" class="button">Explore our approach ${arrow}</a><a class="text-link" href="./phil-pegram.html">Meet Phil Pegram ${arrow}</a></div>
    </div>
    <figure class="hero-visual"><span class="image-tab eyebrow">Built with communities</span><img src="./assets/community.webp" srcset="./assets/community-small.webp 780w, ./assets/community.webp 1500w" sizes="(max-width: 800px) 92vw, 46vw" width="1500" height="784" alt="MOSAIC brand illustration of neighbours talking on a North West terraced street" fetchpriority="high"><span class="image-sticker" aria-hidden="true">NORTH WEST<br>ROOTS.<br>SHARED<br>AMBITION.</span><figcaption>MOSAIC brand illustration</figcaption></figure>
  </div>
</section>
<div class="ribbon" aria-label="Our focus"><span>Community knowledge</span><span class="cross" aria-hidden="true">×</span><span>Research evidence</span><span class="cross last-cross" aria-hidden="true">×</span><span class="ribbon-last">Practical change</span></div>
<section class="intro wrap"><p class="eyebrow">Why MOSAIC exists</p><div class="intro-text"><h2>Opportunity depends on the systems people have to use.</h2><p>Recruitment rules, access to technology and the way services are designed can restrict people’s options. MOSAIC’s purpose is to understand those barriers and work with the people affected to change them.</p><p>Our focus is people furthest from opportunity, including people with criminal records, people facing long-term unemployment and families in deprived communities.</p></div></section>
<section class="poster-stack wrap" aria-labelledby="explore-title"><div class="section-top"><h2 id="explore-title">Find your way in.</h2><p class="eyebrow">The purpose. The approach. The person.</p></div>
  <a class="poster" href="./approach.html#barriers"><div class="poster-content"><span class="poster-number">THE BARRIERS</span><h3>Understand what<br>gets in the way.</h3><p>Work, skills, digital access and the rules that affect people’s options.</p></div><img src="./assets/community.webp" width="1500" height="784" alt="" loading="lazy">${arrow}</a>
  <a class="poster" href="./approach.html#method"><div class="poster-content"><span class="poster-number">THE APPROACH</span><h3>Build with<br>communities.</h3><p>Combine lived experience and research. Agree what to test and how to assess it.</p></div><img src="./assets/mosaic-artwork.webp" width="1024" height="576" alt="" loading="lazy">${arrow}</a>
  <a class="poster" href="./phil-pegram.html"><div class="poster-content"><span class="poster-number">THE FOUNDER</span><h3>Meet<br>Phil Pegram.</h3><p>Insights leader, practitioner-researcher and founder of MOSAIC CIC.</p></div><img src="./assets/phil-pegram.webp" width="1200" height="675" alt="Phil Pegram" loading="lazy">${arrow}</a>
</section>
<section class="founder"><div class="wrap founder-grid"><figure class="portrait"><img src="./assets/phil-pegram.webp" width="1200" height="675" alt="Phil Pegram, founder of MOSAIC CIC" loading="lazy"><figcaption>Phil Pegram / Founder</figcaption></figure><div><p class="eyebrow">The person behind MOSAIC</p><h2>Research experience.<br>A community purpose.</h2><p>Phil is Head of Insights, Analytics and Market Research at TalkTalk and a DBA researcher at Teesside University. His background spans commercial research, analytics and British Army intelligence.</p><p>Through MOSAIC, he applies that research discipline to a different question: what needs to change so people can access opportunity?</p><a class="text-link" href="./phil-pegram.html">Phil’s background and motivation ${arrow}</a></div></div></section>
<section class="principles wrap"><div class="section-top"><h2>How we intend to work.</h2><a class="text-link" href="./approach.html#standards">Our commitments ${arrow}</a></div><div class="principle-grid"><article class="principle"><p class="eyebrow">Participation</p><h3>People help decide<br>what gets researched.</h3><p>Community knowledge should inform the questions, the interpretation and the proposed response. Participation needs clear consent and an explanation of how contributions will be used.</p></article><article class="principle"><p class="eyebrow">Accountability</p><h3>Claims need evidence<br>people can inspect.</h3><p>Our commitment is to explain methods, report limitations and distinguish proposed work from measured results. We’ll publish findings when there is evidence to report.</p></article></div></section>
${cta}`
  },
  {
    file: 'approach.html', title: 'Our approach | MOSAIC CIC',
    description: 'How MOSAIC proposes to research structural barriers, involve communities and test practical responses in North West England.',
    body: `
<section class="page-hero wrap">${breadcrumb('Our approach')}<div class="page-hero-grid"><div><p class="eyebrow">The MOSAIC approach</p><h1>Start with<br>the barrier.</h1><p class="lead">Find out what prevents access, involve the people affected and agree what needs to change.</p></div><figure><img src="./assets/mosaic-artwork.webp" width="1024" height="576" alt="MOSAIC artwork with interlocking gold and green pieces"><figcaption>Pieces for Change / MOSAIC brand artwork</figcaption></figure></div></section>
<section class="section-pad tinted" id="barriers"><div class="wrap"><div class="split"><p class="eyebrow">Our focus</p><div><h2>Examine the rules,<br>the services and the decisions.</h2><p style="margin-top:var(--space-6)">We’re interested in barriers that persist even when someone has taken a course, applied for work or asked for support. Research needs to explain where access breaks down and who can change it.</p></div></div><div class="focus-list"><article class="focus-item"><p class="eyebrow">Work and recruitment</p><h3>Access to employment</h3><p>Questions about recruitment practices, criminal-record disclosure and the experience of looking for work after a long period of unemployment.</p></article><article class="focus-item"><p class="eyebrow">Technology and services</p><h3>Digital access</h3><p>Questions about devices, connectivity, digital skills and what happens when essential services assume everyone can get online.</p></article><article class="focus-item"><p class="eyebrow">Skills and support</p><h3>What happens after training</h3><p>Questions about whether support connects people to opportunities, and which restrictions remain when a course or programme ends.</p></article><article class="focus-item"><p class="eyebrow">Place and opportunity</p><h3>Local conditions</h3><p>Questions about how location, transport and service availability affect the options available to families in deprived communities.</p></article></div></div></section>
<section class="section-pad wrap" id="method"><div class="section-top"><div><p class="eyebrow">Proposed research process</p><h2 style="margin-top:var(--space-4)">From a question<br>to a testable response.</h2></div><p style="max-width:32ch">Each project needs an agreed scope, a proportionate method and a clear decision it can inform.</p></div><div class="approach-steps"><article class="step"><span class="step-number">01</span><h3>Agree the question<br>with the community.</h3><p>Understand who is affected and what they want to change. Decide who needs to participate, how to include them and how their time will be recognised.</p></article><article class="step"><span class="step-number">02</span><h3>Bring experience<br>and evidence together.</h3><p>Use interviews, existing research and relevant public data. Where appropriate, seek information from public bodies. Explain what each method can and cannot establish.</p></article><article class="step"><span class="step-number">03</span><h3>Design a response<br>people can test.</h3><p>Work with communities and organisations to propose a specific change. Agree responsibilities, resources and how to assess whether access improves.</p></article><article class="step"><span class="step-number">04</span><h3>Report what happened<br>and what remains unknown.</h3><p>Compare findings with the original question. Share the evidence, limits and changes needed before recommending wider use.</p></article></div></section>
<section class="section-pad wrap" id="standards"><div class="split"><div><p class="eyebrow">Research commitments</p><h2 style="margin-top:var(--space-5)">Participation needs<br>clear terms.</h2></div><div><p>These commitments describe how we intend to run research. Each study will need its own consent process, data arrangements and safeguarding assessment before recruitment begins.</p><div class="faqs"><details><summary>Consent and use of personal stories</summary><p>We’ll explain the purpose of the research, what taking part involves and how contributions may be used. Stories, quotations and identifying details require specific permission before publication.</p></details><details><summary>Community involvement</summary><p>We’ll agree how people affected can help develop the questions and interpret findings. The project plan should specify how participation is supported and how contributors receive the results.</p></details><details><summary>Evidence and limitations</summary><p>Published findings should explain methods, the people included, gaps in the evidence and alternative explanations. A proposal, a pilot and an evaluated result will be labelled separately.</p></details><details><summary>Partners and accountability</summary><p>Each project should identify who is responsible for decisions, funding and delivery. We’ll seek permission before identifying a partner or using an organisation’s logo.</p></details></div></div></div></section>
${cta}`
  },
  {
    file: 'phil-pegram.html', title: 'Phil Pegram | Founder of MOSAIC CIC',
    description: 'Meet Phil Pegram, MOSAIC CIC founder, Head of Insights, Analytics and Market Research at TalkTalk, and DBA researcher at Teesside University.',
    body: `
<section class="page-hero wrap">${breadcrumb('Phil Pegram')}<div class="page-hero-grid"><div><p class="eyebrow">Founder / MOSAIC CIC</p><h1>Phil<br>Pegram.</h1><p class="lead">Insights leader.<br>Practitioner-researcher.<br>Founder of MOSAIC.</p><a href="${phil}" ${external} class="text-link" style="margin-top:var(--space-6)">Connect with Phil on LinkedIn ${arrow}</a></div><figure><img src="./assets/phil-pegram.webp" width="1200" height="675" alt="Phil Pegram smiling, photographed indoors" fetchpriority="high"><figcaption>Phil Pegram / North West England</figcaption></figure></div></section>
<section class="section-pad tinted"><div class="wrap split"><div><p class="eyebrow">Why MOSAIC</p><h2 style="margin-top:var(--space-5)">Put research<br>to practical use.</h2></div><div><p>Phil founded MOSAIC to understand and address structural barriers to opportunity in North West England. His experience of moving from military to civilian life informs his interest in how systems recognise people’s skills and experience. <a href="https://mosaiccic.co.site/" ${external}>Read the original MOSAIC story</a>.</p><p>MOSAIC gives that purpose a practical focus: research with people furthest from opportunity, understand the rules and decisions affecting them, and develop responses with communities.</p></div></div></section>
<section class="section-pad wrap"><div class="split"><p class="eyebrow">Professional background</p><div><h2>Evidence, organisations<br>and decisions.</h2><p style="margin-top:var(--space-6)">Phil’s work combines customer insight, analytics and market research. He is interested in how organisations use evidence, who is responsible for acting on it and what prevents findings from influencing decisions.</p></div></div><div class="bio-experience"><article class="experience"><p class="eyebrow">Current role</p><h3>TalkTalk</h3><p>Head of Insights, Analytics and Market Research, connecting customer and market evidence to commercial decisions.</p></article><article class="experience"><p class="eyebrow">Doctoral research</p><h3>Teesside University</h3><p>DBA researcher with interests in evidence-based management, organisational identity and AI-enabled organisational change.</p></article><article class="experience"><p class="eyebrow">Research leadership</p><h3>Dentsu</h3><p>Previous senior insight roles in an agency environment, supporting clients’ understanding of customers and markets.</p></article><article class="experience"><p class="eyebrow">Earlier career</p><h3>British Army intelligence</h3><p>Experience in intelligence, evidence assessment and decision support before a career in commercial insight.</p></article></div><p class="independence">These are Phil’s professional and academic affiliations. Their inclusion does not imply funding, partnership or endorsement of MOSAIC by these organisations. <a href="${phil}" ${external}>View Phil’s professional profile</a>.</p></section>
<section class="section-pad wrap"><div class="split"><div><p class="eyebrow">Research, speaking and collaboration</p><h2 style="margin-top:var(--space-5)">A question<br>we can investigate?</h2></div><div><p>Phil welcomes conversations about community research, evidence-based decisions, organisational change and the use of AI in research and analytics.</p><p>For a speaking invitation or proposed collaboration, share the subject, audience, timing and what you want the work to achieve.</p><a class="text-link" href="./contact.html">Get in touch ${arrow}</a></div></div></section>`
  },
  {
    file: 'contact.html', title: 'Get in touch | MOSAIC CIC',
    description: 'Contact MOSAIC CIC or Phil Pegram about community research, collaboration, speaking and barriers to opportunity in North West England.',
    body: `
<section class="page-hero wrap">${breadcrumb('Get in touch')}<p class="eyebrow">Community research / Collaboration / Speaking</p><h1>Let’s talk<br>about the barrier.</h1><p class="lead">Tell us what you’re seeing, who it affects and what you’d like to investigate or change.</p><div class="contact-options"><article class="contact-option"><p class="eyebrow">For communities and organisations</p><h2>Talk to MOSAIC.</h2><p>Community research, proposed partnerships and questions about access to work, skills or services in the North West.</p><a href="${company}" ${external} class="text-link">Visit MOSAIC on LinkedIn ${arrow}</a></article><article class="contact-option"><p class="eyebrow">For research and professional enquiries</p><h2>Talk to Phil.</h2><p>Speaking, research collaboration and conversations about insight, evidence-based decisions and organisational change.</p><a href="${phil}" ${external} class="text-link">Connect with Phil on LinkedIn ${arrow}</a></article></div><p class="contact-note">Contact currently uses LinkedIn. You may need to sign in or connect before sending a message.</p></section>
<section class="section-pad wrap"><div class="split"><div><p class="eyebrow">Before you get in touch</p><h2 style="margin-top:var(--space-5)">Give us enough<br>to understand.</h2></div><div><p>For a research enquiry, describe the place, the barrier and the people affected. Include any relevant evidence and say whether you’re exploring an idea or have a funded brief.</p><p>For speaking or professional enquiries, include the audience, format and proposed date. Please avoid sending sensitive personal information in an initial message.</p><div class="faqs"><details><summary>Can I request individual support?</summary><p>MOSAIC’s focus is research into structural barriers. This website is not a casework, crisis or emergency service and cannot promise individual support.</p></details><details><summary>Can I propose a research project?</summary><p>Yes. Send an outline of the question, the community involved, the decision the research would inform and any timing or funding constraints. A conversation does not commit either party to a project.</p></details><details><summary>Where can I follow updates?</summary><p>Follow <a href="${company}" ${external}>MOSAIC on LinkedIn</a> for organisation updates, or <a href="${phil}" ${external}>Phil’s profile</a> for his professional writing and research interests.</p></details></div></div></div></section>`
  },
  {
    file: 'privacy.html', title: 'Website privacy | MOSAIC CIC',
    description: 'How this MOSAIC website handles browsing, external links and contact.',
    body: `<article class="legal wrap">${breadcrumb('Website privacy')}<p class="eyebrow">Website information / 4 October 2026</p><h1>Website privacy.</h1><p>This page describes this website’s current technical setup. Any future research study will need separate participant information and a study-specific privacy notice.</p><h2>Browsing this site</h2><p>The website does not contain analytics scripts, advertising trackers, embedded social feeds or a contact form. Images and fonts are hosted with the site, and the colour preference lasts for the current page visit without being saved to browser storage.</p><h2>Hosting</h2><p>The hosting provider may process connection information such as IP addresses and technical request logs when serving a page. Once hosted on GitHub Pages, GitHub’s handling of that information is described in the <a href="https://docs.github.com/en/site-policy/privacy-policies/github-general-privacy-statement" ${external}>GitHub General Privacy Statement</a>. A preview hosted elsewhere is subject to that provider’s practices.</p><h2>Contact through LinkedIn</h2><p>Contact links open LinkedIn, which processes information under its own <a href="https://www.linkedin.com/legal/privacy-policy" ${external}>privacy policy</a>. Please send only the information needed to explain your enquiry, and avoid sensitive personal details in an initial message.</p><h2>Questions about information you have shared</h2><p>Contact <a href="${phil}" ${external}>Phil Pegram on LinkedIn</a> to ask about information you have shared with MOSAIC, or to raise a privacy concern. We’ll need to understand the request and confirm any necessary details before responding.</p><h2>Changes to the site</h2><p>If forms, analytics, newsletter subscriptions or other data-processing features are added, this page will need updating before those features are enabled.</p></article>`
  },
  {
    file: 'accessibility.html', title: 'Accessibility | MOSAIC CIC',
    description: 'Accessibility features and how to report an access barrier on the MOSAIC website.',
    body: `<article class="legal wrap">${breadcrumb('Accessibility')}<p class="eyebrow">Website information</p><h1>Accessibility.</h1><p>We want people to be able to read this website and use its links with a keyboard, a screen reader or a touch device. This page describes the features included and how to report a problem.</p><h2>Features included</h2><ul><li>A skip link to get past the navigation.</li><li>Semantic headings and labelled navigation.</li><li>Text alternatives for informative images.</li><li>Visible keyboard focus and a mobile menu that closes with Escape.</li><li>Light and dark colours, using your system preference by default.</li><li>Layouts that adapt to smaller screens and reduced-motion preferences.</li></ul><h2>Known limitations</h2><p>Contact currently depends on LinkedIn, which may require an account. That creates an access barrier for visitors who do not use the service. The website has not had an independent accessibility audit, so these features should not be read as a certification of WCAG compliance.</p><h2>Report a problem</h2><p>If you can access LinkedIn, contact <a href="${phil}" ${external}>Phil Pegram</a> with the page address, the task you were trying to complete and any assistive technology or browser involved. Please say what format or change would help.</p></article>`
  },
  {
    file: '404.html', title: 'Page not found | MOSAIC CIC',
    description: 'This page could not be found. Return to MOSAIC CIC.',
    body: `<section class="not-found wrap"><p class="eyebrow">404 / Page not found</p><h1>This piece<br>is missing.</h1><p>The address may have changed or the page may no longer exist. You can return to the homepage or get in touch.</p><a class="button" href="./index.html">Back to MOSAIC ${arrow}</a></section>`
  }
];

for (const page of pages) {
  const canonical = `https://mosaiccic.com/${page.file === 'index.html' ? '' : page.file}`;
  const jsonLd = { '@context': 'https://schema.org', '@type': page.file === 'phil-pegram.html' ? 'ProfilePage' : 'WebPage', name: page.title, url: canonical, description: page.description, ...(page.file === 'phil-pegram.html' ? { mainEntity: { '@type': 'Person', name: 'Phil Pegram', url: canonical, sameAs: [phil], jobTitle: 'Head of Insights, Analytics and Market Research' } } : {}) };
  const html = `<!doctype html>
<html lang="en-GB" id="top"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="color-scheme" content="light dark"><title>${page.title}</title><meta name="description" content="${page.description}"><meta name="theme-color" content="#123c2c"><link rel="canonical" href="${canonical}">${page.file === '404.html' ? '<meta name="robots" content="noindex">' : ''}<link rel="icon" href="./favicon.svg" type="image/svg+xml"><link rel="preload" href="./assets/fonts/archivo-black.woff2" as="font" type="font/woff2" crossorigin><link rel="stylesheet" href="./base.css"><link rel="stylesheet" href="./style.css"><meta property="og:type" content="website"><meta property="og:site_name" content="MOSAIC CIC"><meta property="og:title" content="${page.title}"><meta property="og:description" content="${page.description}"><meta property="og:url" content="${canonical}"><meta property="og:image" content="https://mosaiccic.com/assets/social-card.jpg"><meta property="og:image:width" content="1200"><meta property="og:image:height" content="630"><meta property="og:image:alt" content="MOSAIC CIC. Pieces for Change. Community-led research in North West England."><meta name="twitter:card" content="summary_large_image"><script type="application/ld+json">${JSON.stringify(jsonLd)}</script><script src="./app.js" defer></script></head><body>${header(page.file)}<main id="main">${page.body}</main>${footer}<script>document.querySelectorAll('.theme-toggle,.menu-toggle').forEach(function(b){b.hidden=false});</script></body></html>`;
  const themedHtml = html
    .replace('<link rel="stylesheet" href="./base.css">', '<script src="./theme.js"></script><link rel="stylesheet" href="./base.css">')
    .replace('the colour preference lasts for the current page visit without being saved to browser storage.', 'a chosen colour theme is included in internal page addresses so it continues across navigation. The site does not save that choice to cookies or browser storage; opening a plain address uses your system preference.');
  const result = page.file === '404.html'
    ? themedHtml.replace('<head>', '<head><base href="/">')
    : themedHtml;
  writeFileSync(join(output, page.file), result);
}
if (output !== root) {
  for (const name of ['base.css', 'style.css', 'app.js', 'theme.js', 'favicon.svg', 'CNAME', '.nojekyll', 'robots.txt', 'sitemap.xml']) copyFileSync(join(root, name), join(output, name));
  cpSync(join(root, 'assets'), join(output, 'assets'), { recursive: true });
}
console.log(`Built ${pages.length} pages in ${output}`);
